import VideoExample from "../assets/video/office.mp4";
import { nanoid } from "nanoid";
export const courseDatas = [
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-orange",
      labelText: "Bestseller"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
    // className: "itemello",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-red",
      labelText: "Chegirmadagi Kurs"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-green",
      labelText: "tavsiya qilingan"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-red",
      labelText: "Chegirmadagi kurs"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: false,
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-green",
      labelText: "tavsiya qilingan"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: false,
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-orange",
      labelText: "Bestseller"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: {
      labelColor: "bg-red",
      labelText: "Chegirmadagi kurs"
    },
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: false,
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: false,
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: false,
    dicountAvailable: "12:04:04",
  },
  {
    id: nanoid(),
    video: VideoExample,
    label: false,
    title: "Biznesda CRM sistemadan foydalanish va o'rnatish",
    trainer: "Ulugbek Samig'janov",
    rating: "4.7",
    ratersNumber: "55,110",
    graduates: "110,000",
    priceLine: "8,600,000",
    price: "1,000,000",
    dicountAvailable: "12:04:04",
  },
];

export const menuCourses = [
  {
    name: "Biznes",
    submenu: [
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
      "IKKI",
    ]
  },
  {
    name: "IT va dasturlash",
    submenu: [
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
      "BIR",
    ]
  },
  {
    name: 'Marketing',
    submenu: [
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
      "uch",
    ]
  },
  {
    name: "Shaxsiy o'sish",
    submenu: [
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
      "to'rt",
    ]
  },
  {
    name: "Ta'lim va ilmiy fanlar",
    submenu: [
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
      "besh",
    ]
  },
  {
    name: "Foto va video",
    submenu: [
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
      "olti",
    ]
  },
  {
    name: "Sog'lik va fitnes",
    submenu: [
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
      "yetti",
    ]
  },
  {
    name: "Boshqa",
    submenu: [
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
      "sakkiz",
    ]
  },
]